- type: dungeonConfig
  id: CPDungeonTest
  generator: !type:PrefabDunGen
    tile: FloorCaveDrought
    roomWhitelist:
      - Mineshaft
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:

  - !type:CorridorPostGen
      tile: FloorCaveDrought
      width: 3

  - !type:DungeonEntrancePostGen
      count: 1
      tile: FloorCaveDrought
      entities:
        - RandomWoodenWall
        - CPDebugExitDungeon

  - !type:RoomEntrancePostGen
      tile: FloorCaveDrought
      entities:
        - RandomWoodenWall

  - !type:EntranceFlankPostGen
      tile: FloorCaveDrought
      entities:
        - RandomWoodenWall

  - !type:ExternalWindowPostGen
      tile: FloorCaveDrought
      entities:
        - RandomWoodenWall

  - !type:BoundaryWallPostGen
      tile: FloorCaveDrought
      wall: CPCaveStoneWall
      cornerWall: CPCaveStoneWall

  - !type:AutoCablingPostGen
      entity: Catwalk

  - !type:JunctionPostGen
      tile: FloorCaveDrought
      width: 3
      entities:
        - RandomWoodenSupport

  - !type:CornerClutterPostGen
      contents:
        - id: RandomStalagmiteOrCrystal
          amount: 1